name: ingenius
favicon: null
layout_spectrum: 0.82287
typography_spectrum: 0.6893617
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#000000'
    - '#0000FF'
    - '#007AFF'
    - '#B3B3B3'
  brandStrength: 1
  lightness: 0.5625
  saturation: 1
  rhythmicContrast: 0
purpose: []
