layout_spectrum: 0.993617
name: ingenius
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0
  lightness: 0.793617
  saturation: 1
  rhythmicContrast: 0.3574468
  brandColors:
    - '#FFFFFF'
    - '#000000'
    - '#0000FF'
    - '#007AFF'
    - '#B3B3B3'
typography_spectrum: 0.6893617
