layout_spectrum: 1
typography_spectrum: 0.4893617
color:
  lightness: 0.6574468
  brandStrength: 0.6680851
  saturation: 0.6
  rhythmicContrast: 0.2787234
  brandColors:
    - '#FFFFFF'
    - '#07046E'
    - '#8B8AC5'
name: ingenius
